/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    isOptional: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, role: {
                    name: "role",
                    type: "Role",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, verified: {
                    name: "verified",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, studentProfile: {
                    name: "studentProfile",
                    type: "StudentProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'user',
                }, mentorProfile: {
                    name: "mentorProfile",
                    type: "MentorProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'user',
                }, employerProfile: {
                    name: "employerProfile",
                    type: "EmployerProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, threads: {
                    name: "threads",
                    type: "Thread",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'author',
                }, answers: {
                    name: "answers",
                    type: "Answer",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'author',
                }, chatRoomsA: {
                    name: "chatRoomsA",
                    type: "ChatRoom",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'userA',
                }, chatRoomsB: {
                    name: "chatRoomsB",
                    type: "ChatRoom",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'userB',
                }, messages: {
                    name: "messages",
                    type: "Message",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'sender',
                }, applications: {
                    name: "applications",
                    type: "Application",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'student',
                }, reportsMade: {
                    name: "reportsMade",
                    type: "Report",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'reporter',
                }, channelsCreated: {
                    name: "channelsCreated",
                    type: "Channel",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, votes: {
                    name: "votes",
                    type: "AnswerVote",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, notifications: {
                    name: "notifications",
                    type: "Notification",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'recipient',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, type: {
                    name: "type",
                    type: "String",
                }, provider: {
                    name: "provider",
                    type: "String",
                }, providerAccountId: {
                    name: "providerAccountId",
                    type: "String",
                }, refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    isOptional: true,
                }, access_token: {
                    name: "access_token",
                    type: "String",
                    isOptional: true,
                }, expires_at: {
                    name: "expires_at",
                    type: "Int",
                    isOptional: true,
                }, token_type: {
                    name: "token_type",
                    type: "String",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, id_token: {
                    name: "id_token",
                    type: "String",
                    isOptional: true,
                }, session_state: {
                    name: "session_state",
                    type: "String",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, provider_providerAccountId: {
                    name: "provider_providerAccountId",
                    fields: ["provider", "providerAccountId"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sessionToken: {
                    name: "sessionToken",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, expires: {
                    name: "expires",
                    type: "DateTime",
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, sessionToken: {
                    name: "sessionToken",
                    fields: ["sessionToken"]
                },
            },
        },
        studentProfile: {
            name: 'StudentProfile', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'studentProfile',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, bio: {
                    name: "bio",
                    type: "String",
                    isOptional: true,
                }, university: {
                    name: "university",
                    type: "String",
                    isOptional: true,
                }, major: {
                    name: "major",
                    type: "String",
                    isOptional: true,
                }, yearOfStudy: {
                    name: "yearOfStudy",
                    type: "Int",
                    isOptional: true,
                }, skills: {
                    name: "skills",
                    type: "String",
                    isArray: true,
                }, cvUrl: {
                    name: "cvUrl",
                    type: "String",
                    isOptional: true,
                }, portfolio: {
                    name: "portfolio",
                    type: "String",
                    isOptional: true,
                }, github: {
                    name: "github",
                    type: "String",
                    isOptional: true,
                }, linkedin: {
                    name: "linkedin",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, applications: {
                    name: "applications",
                    type: "Application",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'studentProfile',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId: {
                    name: "userId",
                    fields: ["userId"]
                },
            },
        },
        mentorProfile: {
            name: 'MentorProfile', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'mentorProfile',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, company: {
                    name: "company",
                    type: "String",
                }, position: {
                    name: "position",
                    type: "String",
                }, yearsOfExperience: {
                    name: "yearsOfExperience",
                    type: "Int",
                }, expertise: {
                    name: "expertise",
                    type: "String",
                    isArray: true,
                }, bio: {
                    name: "bio",
                    type: "String",
                    isOptional: true,
                }, verified: {
                    name: "verified",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, openToChat: {
                    name: "openToChat",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId: {
                    name: "userId",
                    fields: ["userId"]
                },
            },
        },
        employerProfile: {
            name: 'EmployerProfile', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'employerProfile',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, companyId: {
                    name: "companyId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'company',
                }, company: {
                    name: "company",
                    type: "Company",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'employers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "companyId" },
                }, title: {
                    name: "title",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId: {
                    name: "userId",
                    fields: ["userId"]
                },
            },
        },
        company: {
            name: 'Company', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                }, logo: {
                    name: "logo",
                    type: "String",
                    isOptional: true,
                }, website: {
                    name: "website",
                    type: "String",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, industry: {
                    name: "industry",
                    type: "String",
                    isOptional: true,
                }, location: {
                    name: "location",
                    type: "String",
                    isOptional: true,
                }, size: {
                    name: "size",
                    type: "CompanySize",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, verified: {
                    name: "verified",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, employers: {
                    name: "employers",
                    type: "EmployerProfile",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'company',
                }, jobs: {
                    name: "jobs",
                    type: "Job",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'company',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        channel: {
            name: 'Channel', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, category: {
                    name: "category",
                    type: "ChannelCategory",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, visibility: {
                    name: "visibility",
                    type: "ChannelVisibility",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, tags: {
                    name: "tags",
                    type: "String",
                    isArray: true,
                }, iconKey: {
                    name: "iconKey",
                    type: "String",
                    isOptional: true,
                }, approved: {
                    name: "approved",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdById: {
                    name: "createdById",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'channelsCreated',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "createdById" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, threads: {
                    name: "threads",
                    type: "Thread",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'channel',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        thread: {
            name: 'Thread', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, content: {
                    name: "content",
                    type: "String",
                }, tags: {
                    name: "tags",
                    type: "String",
                    isArray: true,
                }, channelId: {
                    name: "channelId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'channel',
                }, channel: {
                    name: "channel",
                    type: "Channel",
                    isDataModel: true,
                    backLink: 'threads',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "channelId" },
                }, authorId: {
                    name: "authorId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'author',
                }, author: {
                    name: "author",
                    type: "User",
                    isDataModel: true,
                    backLink: 'threads',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "authorId" },
                }, isAnonymous: {
                    name: "isAnonymous",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, pinned: {
                    name: "pinned",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, closed: {
                    name: "closed",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, viewCount: {
                    name: "viewCount",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, answers: {
                    name: "answers",
                    type: "Answer",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'thread',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        answer: {
            name: 'Answer', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, content: {
                    name: "content",
                    type: "String",
                }, threadId: {
                    name: "threadId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'thread',
                }, thread: {
                    name: "thread",
                    type: "Thread",
                    isDataModel: true,
                    backLink: 'answers',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "threadId" },
                }, authorId: {
                    name: "authorId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'author',
                }, author: {
                    name: "author",
                    type: "User",
                    isDataModel: true,
                    backLink: 'answers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "authorId" },
                }, isAnonymous: {
                    name: "isAnonymous",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, upvotes: {
                    name: "upvotes",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, accepted: {
                    name: "accepted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, votes: {
                    name: "votes",
                    type: "AnswerVote",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'answer',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        answerVote: {
            name: 'AnswerVote', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'votes',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, answerId: {
                    name: "answerId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'answer',
                }, answer: {
                    name: "answer",
                    type: "Answer",
                    isDataModel: true,
                    backLink: 'votes',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "answerId" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId_answerId: {
                    name: "userId_answerId",
                    fields: ["userId", "answerId"]
                },
            },
        },
        notification: {
            name: 'Notification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, recipientId: {
                    name: "recipientId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'recipient',
                }, recipient: {
                    name: "recipient",
                    type: "User",
                    isDataModel: true,
                    backLink: 'notifications',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "recipientId" },
                }, type: {
                    name: "type",
                    type: "String",
                }, title: {
                    name: "title",
                    type: "String",
                }, body: {
                    name: "body",
                    type: "String",
                    isOptional: true,
                }, link: {
                    name: "link",
                    type: "String",
                    isOptional: true,
                }, read: {
                    name: "read",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        job: {
            name: 'Job', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                }, requirements: {
                    name: "requirements",
                    type: "String",
                    isOptional: true,
                }, benefits: {
                    name: "benefits",
                    type: "String",
                    isOptional: true,
                }, type: {
                    name: "type",
                    type: "JobType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, status: {
                    name: "status",
                    type: "JobStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, location: {
                    name: "location",
                    type: "String",
                    isOptional: true,
                }, salaryRange: {
                    name: "salaryRange",
                    type: "String",
                    isOptional: true,
                }, tags: {
                    name: "tags",
                    type: "String",
                    isArray: true,
                }, companyId: {
                    name: "companyId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'company',
                }, company: {
                    name: "company",
                    type: "Company",
                    isDataModel: true,
                    backLink: 'jobs',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "companyId" },
                }, postedById: {
                    name: "postedById",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, deadline: {
                    name: "deadline",
                    type: "DateTime",
                    isOptional: true,
                }, applications: {
                    name: "applications",
                    type: "Application",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'job',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        application: {
            name: 'Application', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, jobId: {
                    name: "jobId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'job',
                }, job: {
                    name: "job",
                    type: "Job",
                    isDataModel: true,
                    backLink: 'applications',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "jobId" },
                }, studentId: {
                    name: "studentId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'student',
                }, student: {
                    name: "student",
                    type: "User",
                    isDataModel: true,
                    backLink: 'applications',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "studentId" },
                }, studentProfileId: {
                    name: "studentProfileId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'studentProfile',
                }, studentProfile: {
                    name: "studentProfile",
                    type: "StudentProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'applications',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "studentProfileId" },
                }, cvSnapshotUrl: {
                    name: "cvSnapshotUrl",
                    type: "String",
                    isOptional: true,
                }, coverLetter: {
                    name: "coverLetter",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "ApplicationStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, note: {
                    name: "note",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, jobId_studentId: {
                    name: "jobId_studentId",
                    fields: ["jobId", "studentId"]
                },
            },
        },
        chatRoom: {
            name: 'ChatRoom', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userAId: {
                    name: "userAId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'userA',
                }, userA: {
                    name: "userA",
                    type: "User",
                    isDataModel: true,
                    backLink: 'chatRoomsA',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userAId" },
                }, userBId: {
                    name: "userBId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'userB',
                }, userB: {
                    name: "userB",
                    type: "User",
                    isDataModel: true,
                    backLink: 'chatRoomsB',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userBId" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, messages: {
                    name: "messages",
                    type: "Message",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'room',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userAId_userBId: {
                    name: "userAId_userBId",
                    fields: ["userAId", "userBId"]
                },
            },
        },
        message: {
            name: 'Message', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, roomId: {
                    name: "roomId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'room',
                }, room: {
                    name: "room",
                    type: "ChatRoom",
                    isDataModel: true,
                    backLink: 'messages',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "roomId" },
                }, senderId: {
                    name: "senderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'sender',
                }, sender: {
                    name: "sender",
                    type: "User",
                    isDataModel: true,
                    backLink: 'messages',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "senderId" },
                }, content: {
                    name: "content",
                    type: "String",
                }, readAt: {
                    name: "readAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        report: {
            name: 'Report', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, reporterId: {
                    name: "reporterId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'reporter',
                }, reporter: {
                    name: "reporter",
                    type: "User",
                    isDataModel: true,
                    backLink: 'reportsMade',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "reporterId" },
                }, targetType: {
                    name: "targetType",
                    type: "String",
                }, targetId: {
                    name: "targetId",
                    type: "String",
                }, reason: {
                    name: "reason",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "ReportStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, resolution: {
                    name: "resolution",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['Account', 'Session', 'StudentProfile', 'MentorProfile', 'EmployerProfile', 'AnswerVote', 'Notification', 'Application'],
        company: ['Job'],
        channel: ['Thread'],
        thread: ['Answer'],
        answer: ['AnswerVote'],
        job: ['Application'],
        chatRoom: ['Message'],

    },
    authModel: 'User'

};
export default metadata;
