/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, MentorProfile } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateMentorProfile(options?: Omit<(UseMutationOptions<(MentorProfile | undefined), DefaultError, Prisma.MentorProfileCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileCreateArgs, DefaultError, MentorProfile, true>('MentorProfile', 'POST', `${endpoint}/mentorProfile/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyMentorProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MentorProfileCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('MentorProfile', 'POST', `${endpoint}/mentorProfile/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyMentorProfile<TArgs extends Prisma.MentorProfileFindManyArgs, TQueryFnData = Array<Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findMany`, args, options, fetch);
}

export function useInfiniteFindManyMentorProfile<TArgs extends Prisma.MentorProfileFindManyArgs, TQueryFnData = Array<Prisma.MentorProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findMany`, args, options, fetch);
}

export function useSuspenseFindManyMentorProfile<TArgs extends Prisma.MentorProfileFindManyArgs, TQueryFnData = Array<Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyMentorProfile<TArgs extends Prisma.MentorProfileFindManyArgs, TQueryFnData = Array<Prisma.MentorProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findMany`, args, options, fetch);
}

export function useFindUniqueMentorProfile<TArgs extends Prisma.MentorProfileFindUniqueArgs, TQueryFnData = Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueMentorProfile<TArgs extends Prisma.MentorProfileFindUniqueArgs, TQueryFnData = Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findUnique`, args, options, fetch);
}

export function useFindFirstMentorProfile<TArgs extends Prisma.MentorProfileFindFirstArgs, TQueryFnData = Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstMentorProfile<TArgs extends Prisma.MentorProfileFindFirstArgs, TQueryFnData = Prisma.MentorProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/findFirst`, args, options, fetch);
}

export function useUpdateMentorProfile(options?: Omit<(UseMutationOptions<(MentorProfile | undefined), DefaultError, Prisma.MentorProfileUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileUpdateArgs, DefaultError, MentorProfile, true>('MentorProfile', 'PUT', `${endpoint}/mentorProfile/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyMentorProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MentorProfileUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('MentorProfile', 'PUT', `${endpoint}/mentorProfile/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertMentorProfile(options?: Omit<(UseMutationOptions<(MentorProfile | undefined), DefaultError, Prisma.MentorProfileUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileUpsertArgs, DefaultError, MentorProfile, true>('MentorProfile', 'POST', `${endpoint}/mentorProfile/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteMentorProfile(options?: Omit<(UseMutationOptions<(MentorProfile | undefined), DefaultError, Prisma.MentorProfileDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileDeleteArgs, DefaultError, MentorProfile, true>('MentorProfile', 'DELETE', `${endpoint}/mentorProfile/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MentorProfile, Prisma.MentorProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyMentorProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MentorProfileDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MentorProfileDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('MentorProfile', 'DELETE', `${endpoint}/mentorProfile/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MentorProfileDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MentorProfileDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MentorProfileDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateMentorProfile<TArgs extends Prisma.MentorProfileAggregateArgs, TQueryFnData = Prisma.GetMentorProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MentorProfileAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateMentorProfile<TArgs extends Prisma.MentorProfileAggregateArgs, TQueryFnData = Prisma.GetMentorProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MentorProfileAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/aggregate`, args, options, fetch);
}

export function useGroupByMentorProfile<TArgs extends Prisma.MentorProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MentorProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.MentorProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MentorProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MentorProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MentorProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MentorProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MentorProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByMentorProfile<TArgs extends Prisma.MentorProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MentorProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.MentorProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MentorProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MentorProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MentorProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MentorProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MentorProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/groupBy`, args, options, fetch);
}

export function useCountMentorProfile<TArgs extends Prisma.MentorProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MentorProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/count`, args, options, fetch);
}

export function useSuspenseCountMentorProfile<TArgs extends Prisma.MentorProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MentorProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MentorProfileCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MentorProfile', `${endpoint}/mentorProfile/count`, args, options, fetch);
}

export function useCheckMentorProfile<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; company?: string; position?: string; yearsOfExperience?: number; expertise?: string; bio?: string; verified?: boolean; openToChat?: boolean; github?: string; linkedin?: string; achievements?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('MentorProfile', `${endpoint}/mentorProfile/check`, args, options, fetch);
}
